<?php
// $Id$
require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'voipdrupal_ntxuva.scripts.inc');

//@todo: test with Tropo portugese, enable transaltion through voipvoice

/**
 * Implements hook_menu().
 */
function voipdrupal_ntxuva_menu() {
  $items = array();

  $items['admin/config/ntxuva/voipdrupal'] = array(
    'title' => 'Configure VoIP Drupal Ntxuva',
    'description' => 'Settings for VoIP Drupal Ntxuva Module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipdrupal_ntxuva_sms_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Ntxuva Open311 SMS config settings
 *
 */
function voipdrupal_ntxuva_sms_form($form, &$form_state) {
  global $base_url;
  $ntxuva_default_endpoint = $base_url . "/georeport/v2";

  $form['voipdrupal_nxtuva_open311_endpoint'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter Open311 GeoReport v2 endpoint'),
    '#default_value' => variable_get('voipdrupal_nxtuva_open311_endpoint', $ntxuva_default_endpoint),
    '#size' => 100,
    '#maxlength' => 100,
    '#description' => t('Open311 GeoReport v2 API Endpoint for SMS interaction'),
    '#required' => TRUE,
  );

  $form['services'] = array(
    '#type' => 'item',
    '#title' => t('Services'),
    '#markup' => implode(array_map(function ($v, $k) {
      return $k{1} . '=' . $v;
    }, variable_get('voipdrupal_ntxuva_services', array()), array_keys(variable_get('voipdrupal_ntxuva_services', array()))), '<br/>'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Refresh Services'),
    '#submit' => array('voipdrupal_ntxuva_get_services'),
  );

  $form['import_locations'] = array(
    '#type' => 'submit',
    '#value' => t('Import Locations'),
    '#submit' => array('voipdrupal_ntxuva_import_locations'),
  );

  return system_settings_form($form);
}

//@todo: put in install
function voipdrupal_ntxuva_get_services($form, $form_state) {
  $services_json = voipdrupal_ntxuva_call_open311('services');
  $services = array();
  foreach ($services_json as $service_json) {
    $services[$service_json['service_code']] = $service_json['service_name'];
  }
  variable_set('voipdrupal_ntxuva_services', $services);
  drupal_set_message('Services refreshed');
}

function voipdrupal_ntxuva_import_locations($form, $form_state) {
  $url = 'http://mopa.opengov.cc/georeport/v2/locations.json';
  $json = file_get_contents($url);
  $locations_json = json_decode($json, TRUE);
  $quarters = array();
  $containers = array();
//dpm($locations_json);
  foreach ($locations_json as $location) {
    if($location['location_type'] == 'quarter') {
      //quarter is location with a single neighborhood
      $quarters[$location['neighbourhoods'][0]][$location['location_id']] = $location;
    }
    else {
      $containers[$location['neighbourhoods'][0]][$location['location_id']] = $location;
    }
  }

  //dpm($quarters);
  //dpm($containers);
  variable_set('voipdrupal_ntxuva_quarters', $quarters);
  variable_set('voipdrupal_ntxuva_containers', $containers);

  drupal_set_message('Locations imported');
}

function voipdrupal_ntxuva_get_containers_for_neighborhood($neighborhood_id) {
  $neighborhood = voipdrupal_ntxuva_get_neighborhood_name($neighborhood_id);
  $containers = variable_get('voipdrupal_ntxuva_containers', array());
  return isset($containers[$neighborhood]) ? array_values($containers[$neighborhood]) : NULL;
}

function voipdrupal_ntxuva_call_open311($request_id, $type = 'GET', $request = array()) {
  global $base_url;
  $ntxuva_default_endpoint = $base_url . "/georeport/v2";
  $endpoint = variable_get('voipdrupal_nxtuva_open311_endpoint', $ntxuva_default_endpoint);

  $url = "{$endpoint}/{$request_id}.json";

  if ($type == 'POST') {
    $options = array(
      'http' => array(
        'method' => 'POST',
        'content' => json_encode($request),
        'header' => "Content-Type: application/json\r\n" .
          "Accept: application/json\r\n"
      )
    );

    watchdog("voipdrupal_ntxuva", "Preparing JSON: " . print_r($request, TRUE)); // save request for debugging

    $context = stream_context_create($options);
  }
  else {
    $context = NULL;
  }
  // Request status from Open311 Endpoint
  $json = file_get_contents($url, FALSE, $context);
  $res = json_decode($json, TRUE);
  return $res;
}

function voipdrupal_ntxuva_get_location_coordinates($neighborhood_id, $location_id, $type) {
  $neighborhood = voipdrupal_ntxuva_get_neighborhood_name($neighborhood_id);

  if($type == 'quarter') {
    $locations = variable_get('voipdrupal_ntxuva_quarters', array());
  }
  else {
    $locations = variable_get('voipdrupal_ntxuva_containers', array());
  }

  $location_result = array(
    'lat' => $locations[$neighborhood][$location_id]['lat'],
    'long' => $locations[$neighborhood][$location_id]['long'],
  );
  return $location_result;
}

function voipdrupal_ntxuva_get_neighborhood_name($neighborhood_id) {
  $neighborhoods =  array(
    1 => 'Maxaquene A',
    2 => 'Polana Canico B',
    3 => 'Inhagoia B',
    4 => 'Magoanine C',
  );

  return $neighborhoods[$neighborhood_id];
}

